name: news.ycombinator.com ci
on:
  push:
    paths:
      - 'news.ycombinator.com/**'

defaults:
  run:
    working-directory: news.ycombinator.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Run tests
        run: npm test -- --ci

      - name: Bump version number
        run: sed "/^\/\/ @version/c\// @version      $GITHUB_RUN_NUMBER" tampermonkey.js > tampermonkey.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version number